version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # default location of `.github/workflows`
    ignore:
      - dependency-name: "actions/checkout"
    schedule:
      interval: "weekly"
  
  - package-ecosystem: "nuget"
    directory: "/GostGen/source"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
